### ISSUE TITLE
cannot proceed after this.

### ISSUE THREAD

**Issue by ghost** [bunnykek/Download-Gdrive-Protected-PDFs#1]
Uncaught SyntaxError: Identifier 'doc' has already been declared
![Screenshot 2022-06-04 165422](https://user-images.githubusercontent.com/82381632/171996458-a8bf81b9-0a3e-406a-aab4-53650eedc5d2.png)

**Comment by bunnykek** [comment]
I have done some changes in the code. Refresh the page and use the updated one.

**Comment by ghost** [comment]
it is working now.. thanks a lot.
